### ISSUE TITLE
Can't access my scripts and styles when using symlink

### ISSUE THREAD

**Issue by bew** [p3lim/dotjs-universal#16]
Hello,

As the title say, I've set 2 symlink from : 
- `~/.config/dotjs/scripts/   ->   {extensionDirectory}/1.6.1_0/scripts`
- `~/.config/dotjs/styles/   ->   {extensionDirectory}/1.6.1_0/styles`

And I get `ERR_FILE_NOT_FOUND` errors for the **default script** and **style** when loading a page... : 

![bla](https://cloud.githubusercontent.com/assets/9730330/7498801/bc48ba06-f423-11e4-9ae8-d747342cba01.png)

**Comment by p3lim** [comment]
This extension does not work with newer versions of Chrome (40 or higher), as Google decided to break extensions that have modified files.
Because of this, the extension is disbanded and won't be updated in the near future.
See #14.

**Comment by bew** [comment]
I have chromium `Version`**42**`.0.2311.135 (64-bit)` and the extension works **very well** !!
So I don't see any problem with modified files...

it's just when I do a symlink that everything mess up...

I'm on `ArchLinux` with the last chromium version available

**Comment by p3lim** [comment]
If you're on any OS other than Windows, I suggest you look at [defunkt/dotjs](https://github.com/defunkt/dotjs), it is far superior to this fork.
